use_frameworks!

platform :ios, '10.0'

target 'HXWebViewJavascriptBridge_Example' do
  pod 'HXWebViewJavascriptBridge', :path => '../'

  target 'HXWebViewJavascriptBridge_Tests' do
    inherit! :search_paths

    
  end
end
